### ISSUE TITLE
Vehicle Spawn And Delete Money

### ISSUE THREAD

**Issue by Berkeratay** [SpikE-Odets/esx_garbagecrew_v2#7]
This will encourage players not to leave the trucks around.

**Comment by aleexnl** [comment]
So this is an improve and not an issue

**Comment by SpikE-Odets** [comment]
> This will encourage players not to leave the trucks around.

If you are looking for a deposit for spawning the truck.. i have not put that in as it could cause other issues.  If the person pulls a truck out and then disconnects, when they come back they will not have a truck to turn back to get the deposit back.  This comes down to making sure your community will rp the job out right and put the truck back when done.
